apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  namespace: mylocal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
      - name: content-service
        image: fatma111/mylocal-content-service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: mylocal
spec:
  selector:
    app: content-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort
