apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  namespace: mylocal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
      - name: content-service
        image: fatma111/mylocal-content-service:c4645bee2ec53aee69c082fb896bd3cd4653d683
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://app:$(POSTGRES_PASSWORD)@content-database:5432/app"
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: APP_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: mylocal
spec:
  selector:
    app: content-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort
