apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: mylocal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: fatma111/mylocal-gateway:edd5b880183c22ca1975fb4668a505b93b9b8a00
        ports:
        - containerPort: 80
        env:
        - name: APP_ENV
          value: "dev"
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: APP_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: mylocal
spec:
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort
