apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: mylocal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: fatma111/mylocal-user-service:d1bec81fe74c93428d5cc873b55b2ddb03635b79
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://app:$(POSTGRES_PASSWORD)@user-database:5432/app"
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: APP_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: mylocal
spec:
  selector:
    app: user-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort
